// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// do_stop_impl
void do_stop_impl();
RcppExport SEXP _rcpptravis_do_stop_impl() {
BEGIN_RCPP
    do_stop_impl();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcpptravis_do_stop_impl", (DL_FUNC) &_rcpptravis_do_stop_impl, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcpptravis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
