# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_stop_impl <- function() {
    invisible(.Call('_rcpptravis_do_stop_impl', PACKAGE = 'rcpptravis'))
}

