# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cpp_to_http_date <- function(x) {
    .Call(`_rcpptravis_Cpp_to_http_date`, x)
}

Cpp_from_http_date <- function(x) {
    .Call(`_rcpptravis_Cpp_from_http_date`, x)
}

format_cookies <- function(cookies) {
    .Call(`_rcpptravis_format_cookies`, cookies)
}

do_stop_impl <- function() {
    invisible(.Call(`_rcpptravis_do_stop_impl`))
}

